package com.white5703.akyuu.Dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COUNT".
*/
public class CountDao extends AbstractDao<Count, Void> {

    public static final String TABLENAME = "COUNT";

    /**
     * Properties of entity Count.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property ItemCount = new Property(0, long.class, "itemCount", false, "ITEM_COUNT");
        public final static Property PrioritySum = new Property(1, long.class, "prioritySum", false, "PRIORITY_SUM");
    }

    private DaoSession daoSession;


    public CountDao(DaoConfig config) {
        super(config);
    }
    
    public CountDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COUNT\" (" + //
                "\"ITEM_COUNT\" INTEGER NOT NULL ," + // 0: itemCount
                "\"PRIORITY_SUM\" INTEGER NOT NULL );"); // 1: prioritySum
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COUNT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Count entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getItemCount());
        stmt.bindLong(2, entity.getPrioritySum());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Count entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getItemCount());
        stmt.bindLong(2, entity.getPrioritySum());
    }

    @Override
    protected final void attachEntity(Count entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public Count readEntity(Cursor cursor, int offset) {
        Count entity = new Count( //
            cursor.getLong(offset + 0), // itemCount
            cursor.getLong(offset + 1) // prioritySum
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Count entity, int offset) {
        entity.setItemCount(cursor.getLong(offset + 0));
        entity.setPrioritySum(cursor.getLong(offset + 1));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(Count entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(Count entity) {
        return null;
    }

    @Override
    public boolean hasKey(Count entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
