package com.white5703.akyuu.Dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.white5703.akyuu.Dao.Count;
import com.white5703.akyuu.Dao.Note;

import com.white5703.akyuu.Dao.CountDao;
import com.white5703.akyuu.Dao.NoteDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig countDaoConfig;
    private final DaoConfig noteDaoConfig;

    private final CountDao countDao;
    private final NoteDao noteDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        countDaoConfig = daoConfigMap.get(CountDao.class).clone();
        countDaoConfig.initIdentityScope(type);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        countDao = new CountDao(countDaoConfig, this);
        noteDao = new NoteDao(noteDaoConfig, this);

        registerDao(Count.class, countDao);
        registerDao(Note.class, noteDao);
    }
    
    public void clear() {
        countDaoConfig.clearIdentityScope();
        noteDaoConfig.clearIdentityScope();
    }

    public CountDao getCountDao() {
        return countDao;
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

}
