package com.white5703.akyuu.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;
import com.white5703.akyuu.entity.Note;
import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "NOTE".
*/
public class NoteDao extends AbstractDao<Note, Long> {

    public static final String TABLENAME = "NOTE";

    private DaoSession daoSession;

    public NoteDao(DaoConfig config) {
        super(config);
    }

    public NoteDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NOTE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
            "\"BRIEF\" TEXT," + // 1: brief
            "\"DETAIL\" TEXT," + // 2: detail
                "\"TAG\" TEXT," + // 3: tag
            "\"PRIORITY\" INTEGER NOT NULL ," + // 4: priority
            "\"UPDATETIME\" INTEGER);"); // 5: updatetime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NOTE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Note entity) {
        stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }

        String brief = entity.getBrief();
        if (brief != null) {
            stmt.bindString(2, brief);
        }

        String detail = entity.getDetail();
        if (detail != null) {
            stmt.bindString(3, detail);
        }

        String tag = entity.getTag();
        if (tag != null) {
            stmt.bindString(4, tag);
        }
        stmt.bindLong(5, entity.getPriority());

        java.util.Date updatetime = entity.getUpdatetime();
        if (updatetime != null) {
            stmt.bindLong(6, updatetime.getTime());
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Note entity) {
        stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }

        String brief = entity.getBrief();
        if (brief != null) {
            stmt.bindString(2, brief);
        }

        String detail = entity.getDetail();
        if (detail != null) {
            stmt.bindString(3, detail);
        }

        String tag = entity.getTag();
        if (tag != null) {
            stmt.bindString(4, tag);
        }
        stmt.bindLong(5, entity.getPriority());

        java.util.Date updatetime = entity.getUpdatetime();
        if (updatetime != null) {
            stmt.bindLong(6, updatetime.getTime());
        }
    }

    @Override
    public Note readEntity(Cursor cursor, int offset) {
        Note entity = new Note( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // brief
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // detail
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // tag
            cursor.getInt(offset + 4), // priority
            cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5))
            // updatetime
        );
        return entity;
    }

    @Override
    protected final void attachEntity(Note entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public void readEntity(Cursor cursor, Note entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBrief(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDetail(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTag(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPriority(cursor.getInt(offset + 4));
        entity.setUpdatetime(
            cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)));
    }

    /**
     * Properties of entity Note.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Brief = new Property(1, String.class, "brief", false, "BRIEF");
        public final static Property Detail =
            new Property(2, String.class, "detail", false, "DETAIL");
        public final static Property Tag = new Property(3, String.class, "tag", false, "TAG");
        public final static Property Priority =
            new Property(4, int.class, "priority", false, "PRIORITY");
        public final static Property Updatetime =
            new Property(5, java.util.Date.class, "updatetime", false, "UPDATETIME");
    }
    
    @Override
    protected final Long updateKeyAfterInsert(Note entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Note entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Note entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
