language: android

android:
    components:
    # The build tools version used by your project
    - build-tools-28.0.3
    # The SDK version used to compile your project
    - android-28
    # Additional components
    - extra-android-m2repository

before_script:
    # Change Gradle wrapper permissions
    - chmod +x gradlew

script: ./gradlew clean build